use serde_json::Value;
use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let data_dir = manifest_dir.join("src").join("DataJson");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("out dir"));
    let generated = out_dir.join("sdep_api.rs");

    let mut output = String::new();
    output.push_str("// Auto-generated by build.rs\n");
    output.push_str("#[allow(non_snake_case)]\n");

    if let Ok(entries) = fs::read_dir(&data_dir) {
        let mut files = Vec::new();
        for entry in entries.flatten() {
            let path = entry.path();
            let is_json = path
                .extension()
                .and_then(|ext| ext.to_str())
                .map(|ext| ext.eq_ignore_ascii_case("json"))
                .unwrap_or(false);
            if is_json {
                files.push(path);
            }
        }
        files.sort();

        for file in &files {
            println!("cargo:rerun-if-changed={}", file.display());
            if let Some(chunk) = generate_for_file(file) {
                output.push_str(&chunk);
            }
        }
    } else {
        println!("cargo:rerun-if-changed={}", data_dir.display());
    }

    fs::write(&generated, output).expect("write generated api");
}

fn generate_for_file(path: &Path) -> Option<String> {
    let text = fs::read_to_string(path).ok()?;
    let json: Value = serde_json::from_str(&text).ok()?;

    let header = json.get("header")?.as_object()?;
    let database_name = header.get("databaseName")?.as_str()?;
    let dataset = normalize_name(database_name);
    if dataset.is_empty() {
        return None;
    }

    let records = json.get("records")?.as_array()?;
    let mut fields = Vec::new();
    let mut seen = HashSet::new();
    let mut field_types = std::collections::HashMap::new();

    for record in records {
        let object = record.as_object()?;
        for (key, _value) in object {
            let normalized = normalize_name(key);
            if normalized.is_empty() || !seen.insert(normalized.clone()) {
                continue;
            }
            fields.push(normalized.clone());
            field_types.insert(normalized, FieldType::Numeric);
        }
        for (key, value) in object {
            let normalized = normalize_name(key);
            if normalized.is_empty() {
                continue;
            }
            let entry = field_types.entry(normalized).or_insert(FieldType::Numeric);
            if matches!(value, Value::String(_)) {
                *entry = FieldType::String;
            }
        }
    }

    let mut out = String::new();
    out.push_str(&format!(
        "#[unsafe(no_mangle)]\npub extern \"C\" fn sdep_get_{}_ids(buffer: *mut u16, buffer_len: usize) -> i32 {{\n    crate::lookup_ids(\"{}\", buffer, buffer_len)\n}}\n\n",
        dataset, dataset
    ));

    if fields.iter().any(|field| field == "model") {
        out.push_str(&format!(
            "#[unsafe(no_mangle)]\npub extern \"C\" fn sdep_get_{}_model_list(buffer: *mut u16, buffer_len: usize) -> i32 {{\n    crate::lookup_dropdown_list(\"{}\", \"model\", buffer, buffer_len)\n}}\n\n",
            dataset, dataset
        ));
    }

    for normalized in fields {
        match field_types.get(&normalized) {
            Some(FieldType::Numeric) => {
                out.push_str(&format!(
                    "#[unsafe(no_mangle)]\npub extern \"C\" fn sdep_get_{}_{}(id: *const ::core::ffi::c_char, out: *mut f64) -> i32 {{\n    crate::lookup_numeric(\"{}\", \"{}\", id, out)\n}}\n\n",
                    dataset, normalized, dataset, normalized
                ));
            }
            _ => {
                out.push_str(&format!(
                    "#[unsafe(no_mangle)]\npub extern \"C\" fn sdep_get_{}_{}(id: *const ::core::ffi::c_char, buffer: *mut u16, buffer_len: usize) -> i32 {{\n    crate::lookup_string(\"{}\", \"{}\", id, buffer, buffer_len)\n}}\n\n",
                    dataset, normalized, dataset, normalized
                ));
            }
        }
    }

    Some(out)
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum FieldType {
    Numeric,
    String,
}

fn normalize_name(value: &str) -> String {
    let lowered = value.trim().to_ascii_lowercase();
    if lowered == "id" {
        return "id".to_owned();
    }

    match lowered.as_str() {
        "vmp v" => "vmp".to_owned(),
        "voc v" => "voc".to_owned(),
        "imp a" => "imp".to_owned(),
        "isc a" => "isc".to_owned(),
        _ => {
            let mut out = String::with_capacity(lowered.len());
            let mut previous_underscore = false;
            for ch in lowered.chars() {
                let mapped = if ch.is_ascii_alphanumeric() {
                    ch
                } else {
                    '_'
                };
                if mapped == '_' {
                    if !previous_underscore {
                        out.push(mapped);
                        previous_underscore = true;
                    }
                } else {
                    out.push(mapped);
                    previous_underscore = false;
                }
            }
            out.trim_matches('_').to_owned()
        }
    }
}
