use serde_json::Value;
use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let data_dir = manifest_dir.join("src").join("DataJson");
    let repo_root = manifest_dir
        .parent()
        .and_then(|path| path.parent())
        .map(PathBuf::from)
        .unwrap_or_else(|| manifest_dir.clone());
    let vba_dirs = [repo_root.join("temp"), repo_root.join("VBA")];
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("out dir"));
    let generated = out_dir.join("sdep_api.rs");

    let mut output = String::new();
    output.push_str("// Auto-generated by build.rs\n");
    output.push_str("#[allow(non_snake_case)]\n");
    println!("cargo:rerun-if-changed={}", data_dir.display());

    let mut vba_modules = Vec::new();

    if let Ok(entries) = fs::read_dir(&data_dir) {
        let mut files = Vec::new();
        for entry in entries.flatten() {
            let path = entry.path();
            let is_json = path
                .extension()
                .and_then(|ext| ext.to_str())
                .map(|ext| ext.eq_ignore_ascii_case("json"))
                .unwrap_or(false);
            if is_json {
                files.push(path);
            }
        }
        files.sort();

        for file in &files {
            println!("cargo:rerun-if-changed={}", file.display());
            if let Some(info) = dataset_info(file) {
                output.push_str(&generate_for_file(&info));
                if let Some(module) = generate_vba_module(&info) {
                    vba_modules.push(module);
                }
            }
        }
    } else {
        println!("cargo:rerun-if-changed={}", data_dir.display());
    }

    fs::write(&generated, output).expect("write generated api");

    if !vba_modules.is_empty() {
        for vba_dir in &vba_dirs {
            fs::create_dir_all(vba_dir).expect("create vba output directory");
            for (file_name, contents) in &vba_modules {
                fs::write(vba_dir.join(file_name), contents).expect("write vba module");
            }
        }
    }
}

struct DatasetInfo {
    dataset: String,
    fields: Vec<String>,
    field_types: std::collections::HashMap<String, FieldType>,
    sample_id: String,
    sample_numeric_field: Option<String>,
}

fn dataset_info(path: &Path) -> Option<DatasetInfo> {
    let text = fs::read_to_string(path).ok()?;
    let json: Value = serde_json::from_str(&text).ok()?;

    let header = json.get("header")?.as_object()?;
    let database_name = header.get("databaseName")?.as_str()?;
    let dataset = normalize_name(database_name);
    if dataset.is_empty() {
        return None;
    }

    let records = json.get("records")?.as_array()?;
    let mut fields = Vec::new();
    let mut seen = HashSet::new();
    let mut field_types = std::collections::HashMap::new();
    let mut sample_id = String::new();

    for record in records {
        let object = record.as_object()?;
        for (key, _value) in object {
            let normalized = normalize_name(key);
            if normalized.is_empty() || !seen.insert(normalized.clone()) {
                continue;
            }
            fields.push(normalized.clone());
            field_types.insert(normalized, FieldType::Numeric);
        }
        for (key, value) in object {
            let normalized = normalize_name(key);
            if normalized.is_empty() {
                continue;
            }
            if normalized == "id" && sample_id.is_empty() {
                if let Some(id) = value.as_str() {
                    sample_id = id.to_owned();
                }
            }
            let entry = field_types.entry(normalized).or_insert(FieldType::Numeric);
            if matches!(value, Value::String(_)) {
                *entry = FieldType::String;
            }
        }
    }

    let sample_numeric_field = fields
        .iter()
        .find(|field| matches!(field_types.get(*field), Some(FieldType::Numeric)))
        .cloned();

    Some(DatasetInfo {
        dataset,
        fields,
        field_types,
        sample_id,
        sample_numeric_field,
    })
}

fn generate_for_file(info: &DatasetInfo) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "#[unsafe(no_mangle)]\npub extern \"C\" fn sdep_get_{}_ids(buffer: *mut u16, buffer_len: usize) -> i32 {{\n    crate::lookup_ids(\"{}\", buffer, buffer_len)\n}}\n\n",
        info.dataset, info.dataset
    ));

    if info.fields.iter().any(|field| field == "model") {
        out.push_str(&format!(
            "#[unsafe(no_mangle)]\npub extern \"C\" fn sdep_get_{}_model_list(buffer: *mut u16, buffer_len: usize) -> i32 {{\n    crate::lookup_dropdown_list(\"{}\", \"model\", buffer, buffer_len)\n}}\n\n",
            info.dataset, info.dataset
        ));
    }

    for normalized in &info.fields {
        match info.field_types.get(normalized) {
            Some(FieldType::Numeric) => {
                out.push_str(&format!(
                    "#[unsafe(no_mangle)]\npub extern \"C\" fn sdep_get_{}_{}(id: *const ::core::ffi::c_char, out: *mut f64) -> i32 {{\n    crate::lookup_numeric(\"{}\", \"{}\", id, out)\n}}\n\n",
                    info.dataset, normalized, info.dataset, normalized
                ));
            }
            _ => {
                out.push_str(&format!(
                    "#[unsafe(no_mangle)]\npub extern \"C\" fn sdep_get_{}_{}(id: *const ::core::ffi::c_char, buffer: *mut u16, buffer_len: usize) -> i32 {{\n    crate::lookup_string(\"{}\", \"{}\", id, buffer, buffer_len)\n}}\n\n",
                    info.dataset, normalized, info.dataset, normalized
                ));
            }
        }
    }

    out
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum FieldType {
    Numeric,
    String,
}

fn generate_vba_module(info: &DatasetInfo) -> Option<(String, String)> {
    let module_name = vba_module_name(&info.dataset)?;
    let dataset_pascal = to_pascal_case(&info.dataset);
    let mut out = String::new();

    out.push_str(&format!("Attribute VB_Name = \"{}\"\n", module_name));
    out.push_str("Option Explicit\n\n");
    out.push_str("Private Const DEFAULT_BUFFER_LENGTH As Long = 65535\n\n");
    out.push_str("#If VBA7 Then\n");
    out.push_str(&format!(
        "    Private Declare PtrSafe Function sdep_get_{}_ids Lib \"sdep_engine.dll\" (ByVal buffer As LongPtr, ByVal buffer_len As LongPtr) As Long\n",
        info.dataset
    ));
    if info.fields.iter().any(|field| field == "model") {
        out.push_str(&format!(
            "    Private Declare PtrSafe Function sdep_get_{}_model_list Lib \"sdep_engine.dll\" (ByVal buffer As LongPtr, ByVal buffer_len As LongPtr) As Long\n",
            info.dataset
        ));
    }
    for field in &info.fields {
        let field_name = field.as_str();
        match info.field_types.get(field) {
            Some(FieldType::Numeric) => {
                out.push_str(&format!(
                    "    Private Declare PtrSafe Function sdep_get_{}_{} Lib \"sdep_engine.dll\" (ByVal id As LongPtr, ByRef out_value As Double) As Long\n",
                    info.dataset, field_name
                ));
            }
            _ => {
                out.push_str(&format!(
                    "    Private Declare PtrSafe Function sdep_get_{}_{} Lib \"sdep_engine.dll\" (ByVal id As LongPtr, ByVal buffer As LongPtr, ByVal buffer_len As LongPtr) As Long\n",
                    info.dataset, field_name
                ));
            }
        }
    }
    out.push_str("#Else\n");
    out.push_str(&format!(
        "    Private Declare Function sdep_get_{}_ids Lib \"sdep_engine.dll\" (ByVal buffer As Long, ByVal buffer_len As Long) As Long\n",
        info.dataset
    ));
    if info.fields.iter().any(|field| field == "model") {
        out.push_str(&format!(
            "    Private Declare Function sdep_get_{}_model_list Lib \"sdep_engine.dll\" (ByVal buffer As Long, ByVal buffer_len As Long) As Long\n",
            info.dataset
        ));
    }
    for field in &info.fields {
        let field_name = field.as_str();
        match info.field_types.get(field) {
            Some(FieldType::Numeric) => {
                out.push_str(&format!(
                    "    Private Declare Function sdep_get_{}_{} Lib \"sdep_engine.dll\" (ByVal id As Long, ByRef out_value As Double) As Long\n",
                    info.dataset, field_name
                ));
            }
            _ => {
                out.push_str(&format!(
                    "    Private Declare Function sdep_get_{}_{} Lib \"sdep_engine.dll\" (ByVal id As Long, ByVal buffer As Long, ByVal buffer_len As Long) As Long\n",
                    info.dataset, field_name
                ));
            }
        }
    }
    out.push_str("#End If\n\n");
    out.push_str("Private Function TrimNullTerminator(ByVal text As String) As String\n");
    out.push_str("    Dim terminator As Long\n");
    out.push_str("    terminator = InStr(1, text, vbNullChar, vbBinaryCompare)\n");
    out.push_str("    If terminator > 0 Then\n");
    out.push_str("        TrimNullTerminator = Left$(text, terminator - 1)\n");
    out.push_str("    Else\n");
    out.push_str("        TrimNullTerminator = text\n");
    out.push_str("    End If\n");
    out.push_str("End Function\n\n");
    out.push_str("Private Function ToCStringBytes(ByVal text As String) As Byte()\n");
    out.push_str("    Dim bytes() As Byte\n");
    out.push_str("    If Len(text) = 0 Then\n");
    out.push_str("        ReDim bytes(0 To 0)\n");
    out.push_str("        bytes(0) = 0\n");
    out.push_str("    Else\n");
    out.push_str("        bytes = StrConv(text, vbFromUnicode)\n");
    out.push_str("        ReDim Preserve bytes(0 To UBound(bytes) + 1)\n");
    out.push_str("        bytes(UBound(bytes)) = 0\n");
    out.push_str("    End If\n");
    out.push_str("    ToCStringBytes = bytes\n");
    out.push_str("End Function\n\n");

    out.push_str(&format!(
        "Public Function Get{}Ids(ByRef value As String) As Long\n",
        dataset_pascal
    ));
    out.push_str("    Dim buffer As String\n");
    out.push_str("    buffer = String$(DEFAULT_BUFFER_LENGTH, vbNullChar)\n");
    out.push_str(&format!(
        "    Get{}Ids = sdep_get_{}_ids(StrPtr(buffer), Len(buffer))\n",
        dataset_pascal, info.dataset
    ));
    out.push_str("    value = TrimNullTerminator(buffer)\n");
    out.push_str("End Function\n\n");

    if info.fields.iter().any(|field| field == "model") {
        out.push_str(&format!(
            "Public Function Get{}ModelList(ByRef value As String) As Long\n",
            dataset_pascal
        ));
        out.push_str("    Dim buffer As String\n");
        out.push_str("    buffer = String$(DEFAULT_BUFFER_LENGTH, vbNullChar)\n");
        out.push_str(&format!(
            "    Get{}ModelList = sdep_get_{}_model_list(StrPtr(buffer), Len(buffer))\n",
            dataset_pascal, info.dataset
        ));
        out.push_str("    value = TrimNullTerminator(buffer)\n");
        out.push_str("End Function\n\n");
    }

    for field in &info.fields {
        let field_pascal = to_pascal_case(field);
        match info.field_types.get(field) {
            Some(FieldType::Numeric) => {
                out.push_str(&format!(
                    "Public Function Get{}{}(ByVal recordId As String, ByRef value As Double) As Long\n",
                    dataset_pascal, field_pascal
                ));
                out.push_str("    Dim idBytes() As Byte\n");
                out.push_str("    idBytes = ToCStringBytes(recordId)\n");
                out.push_str(&format!(
                    "    Get{}{} = sdep_get_{}_{}(VarPtr(idBytes(0)), value)\n",
                    dataset_pascal, field_pascal, info.dataset, field
                ));
                out.push_str("End Function\n\n");
            }
            _ => {
                out.push_str(&format!(
                    "Public Function Get{}{}(ByVal recordId As String, ByRef value As String) As Long\n",
                    dataset_pascal, field_pascal
                ));
                out.push_str("    Dim idBytes() As Byte\n");
                out.push_str("    Dim buffer As String\n");
                out.push_str("    idBytes = ToCStringBytes(recordId)\n");
                out.push_str("    buffer = String$(DEFAULT_BUFFER_LENGTH, vbNullChar)\n");
                out.push_str(&format!(
                    "    Get{}{} = sdep_get_{}_{}(VarPtr(idBytes(0)), StrPtr(buffer), Len(buffer))\n",
                    dataset_pascal, field_pascal, info.dataset, field
                ));
                out.push_str("    value = TrimNullTerminator(buffer)\n");
                out.push_str("End Function\n\n");
            }
        }
    }

    out.push_str(&format!(
        "Public Sub Test{}()\n    Dim status As Long\n    Dim ids As String\n    Dim models As String\n    Dim manufacturer As String\n    Dim model As String\n    Dim numeric_value As Double\n\n    EnsureDllInitialized\n\n    status = Get{}Ids(ids)\n    RaiseIfFailed status, \"Test{}\"\n    status = Get{}ModelList(models)\n    RaiseIfFailed status, \"Test{}\"\n    status = Get{}Manufacturer(\"{}\", manufacturer)\n    RaiseIfFailed status, \"Test{}\"\n    status = Get{}Model(\"{}\", model)\n    RaiseIfFailed status, \"Test{}\"\n",
        dataset_pascal,
        dataset_pascal,
        dataset_pascal,
        dataset_pascal,
        dataset_pascal,
        dataset_pascal,
        info.sample_id,
        dataset_pascal,
        dataset_pascal,
        info.sample_id,
        dataset_pascal
    ));

    if let Some(field) = &info.sample_numeric_field {
        let field_pascal = to_pascal_case(field);
        out.push_str(&format!(
            "    status = Get{}{}(\"{}\", numeric_value)\n    RaiseIfFailed status, \"Test{}\"\n",
            dataset_pascal, field_pascal, info.sample_id, dataset_pascal
        ));
    }

    out.push_str(&format!(
        "    MsgBox _\n        \"IDs: \" & ids & vbCrLf & _\n        \"Models: \" & models & vbCrLf & _\n        \"Manufacturer: \" & manufacturer & vbCrLf & _\n        \"Model: \" & model & vbCrLf & _\n        \"Numeric value: \" & CStr(numeric_value), vbInformation, \"SDEP {} Test\"\nEnd Sub\n\n",
        dataset_pascal
    ));

    let file_name = format!("{}.bas", module_name);
    Some((file_name, out))
}

fn vba_module_name(dataset: &str) -> Option<String> {
    match dataset {
        "battery_disconnect_switches" | "optimizers" | "pv_disconnect_switches" | "rsd" => {
            Some(format!("mod{}", to_pascal_case(dataset)))
        }
        _ => None,
    }
}

fn to_pascal_case(value: &str) -> String {
    value
        .split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => {
                    let mut chunk = String::new();
                    chunk.push(first.to_ascii_uppercase());
                    chunk.push_str(&chars.as_str().to_ascii_lowercase());
                    chunk
                }
                None => String::new(),
            }
        })
        .collect()
}

fn normalize_name(value: &str) -> String {
    let lowered = value.trim().to_ascii_lowercase();
    if lowered == "id" {
        return "id".to_owned();
    }

    match lowered.as_str() {
        "vmp v" => "vmp".to_owned(),
        "voc v" => "voc".to_owned(),
        "imp a" => "imp".to_owned(),
        "isc a" => "isc".to_owned(),
        _ => {
            let mut out = String::with_capacity(lowered.len());
            let mut previous_underscore = false;
            for ch in lowered.chars() {
                let mapped = if ch.is_ascii_alphanumeric() {
                    ch
                } else {
                    '_'
                };
                if mapped == '_' {
                    if !previous_underscore {
                        out.push(mapped);
                        previous_underscore = true;
                    }
                } else {
                    out.push(mapped);
                    previous_underscore = false;
                }
            }
            out.trim_matches('_').to_owned()
        }
    }
}
